document.documentElement.classList.add('js');
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');
function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Apri menu');document.body.style.overflow=''}
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Chiudi menu':'Apri menu');document.body.style.overflow=open?'hidden':'';if(open)nav.querySelector('a').focus()});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();toggle.focus()}});
window.addEventListener('resize',()=>{if(innerWidth>820)closeMenu()});
const tabs=[...document.querySelectorAll('.menu-tab')],panels=[...document.querySelectorAll('.menu-panel')];
function select(tab){tabs.forEach(t=>{const on=t===tab;t.classList.toggle('active',on);t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1});panels.forEach(p=>p.classList.toggle('active',p.dataset.panel===tab.dataset.menu))}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;if(e.key==='ArrowLeft')j=(i-1+tabs.length)%tabs.length;if(e.key==='Home')j=0;if(e.key==='End')j=tabs.length-1;if(j!==undefined){e.preventDefault();select(tabs[j]);tabs[j].focus()}})});
const form=document.querySelector('#request-form');let calendarUrl;
const pad=value=>String(value).padStart(2,'0');
function calendarStamp(dateValue,timeValue,offsetMinutes=0){const [y,m,d]=dateValue.split('-').map(Number),[h,min]=timeValue.split(':').map(Number);const value=new Date(Date.UTC(y,m-1,d,h,min)+offsetMinutes*60000);return `${value.getUTCFullYear()}${pad(value.getUTCMonth()+1)}${pad(value.getUTCDate())}T${pad(value.getUTCHours())}${pad(value.getUTCMinutes())}00`}
if(form){const date=document.querySelector('#visit-date'),time=document.querySelector('#visit-time'),result=document.querySelector('#request-result');const now=new Date();date.min=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`;
form.addEventListener('input',()=>{result.hidden=true;document.querySelector('#request-error').textContent=''});
form.addEventListener('submit',e=>{e.preventDefault();const when=new Date(`${date.value}T${time.value}`);if(!Number.isFinite(when.getTime())||when<=new Date()){document.querySelector('#request-error').textContent='Scegli un giorno e un orario futuri.';result.hidden=true;return}const people=document.querySelector('#party-size').value;const displayDate=date.value.split('-').reverse().join('/');const text=`Ciao Mondo Bongo, vorrei chiedere disponibilità per ${people} persone il ${displayDate} alle ${time.value}. Potete confermare? Grazie!`;document.querySelector('#request-preview').textContent=text;document.querySelector('#request-link').href=`https://wa.me/393289499016?text=${encodeURIComponent(text)}`;
const startStamp=calendarStamp(date.value,time.value),endStamp=calendarStamp(date.value,time.value,120);const calendarDetails='Promemoria personale per una richiesta da confermare direttamente con Mondo Bongo. Questo evento non costituisce una prenotazione.';const calendarLocation='Via Nazionale Adriatica Sud, 107, 66023 Francavilla al Mare (CH)';const googleParams=new URLSearchParams({action:'TEMPLATE',text:'Mondo Bongo - richiesta DA CONFERMARE',dates:`${startStamp}/${endStamp}`,ctz:'Europe/Rome',details:calendarDetails,location:calendarLocation});document.querySelector('#google-calendar-link').href=`https://calendar.google.com/calendar/render?${googleParams.toString()}`;
if(calendarUrl)URL.revokeObjectURL(calendarUrl);const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Punto Due Studio//Richiesta demo//IT','BEGIN:VEVENT',`UID:${Date.now()}@mondobongo-demo`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Europe/Rome:${startStamp}`,`DTEND;TZID=Europe/Rome:${endStamp}`,'SUMMARY:Mondo Bongo - richiesta DA CONFERMARE',`DESCRIPTION:${calendarDetails}`,`LOCATION:${calendarLocation}`,'STATUS:TENTATIVE','END:VEVENT','END:VCALENDAR'].join('\r\n');calendarUrl=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));document.querySelector('#calendar-link').href=calendarUrl;result.hidden=false;document.querySelector('#request-link').focus()})}
